server:
  port: 8888
  tomcat:
    uri-encoding: UTF-8
debug: true
spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/graduation?serverTimezone=UTC&useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true
    driver-class-name: com.mysql.cj.jdbc.Driver
  messages:
    basename: i18n.login
  mvc:
    format:
      date: yyyy-MM-dd
  jackson:
    date-format: yyyy-MM-dd
    time-zone: GMT+8
  thymeleaf:
    cache: false
  servlet:
    multipart:
      max-file-size: 2GB
      max-request-size: 40GB
mybatis-plus:
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mybatis/mapper/*.xml
